import { getRandomInt, } from '~/utils/utils'

export const defaultValues = {
  name: '',
  week: [
    {
      name: '',
      isTemplate: false,
      day: [
        {
          isRestDay: true,
          exercise: [],
        },
        {
          isRestDay: true,
          exercise: [],
        },
        {
          isRestDay: true,
          exercise: [],
        },
        {
          isRestDay: true,
          exercise: [],
        },
        {
          isRestDay: true,
          exercise: [],
        },
        {
          isRestDay: true,
          exercise: [],
        },
        {
          isRestDay: true,
          exercise: [],
        },
      ],
    },
  ],
}

export const defaultLifts = [
  'squat',
  'bench',
  'deadlift',
  'front squat',
  'deficit deadlift',
  'pause squat',
  'pause front squat',
  'close grip bench',
  'saftety bar squat',
  'paused deficit deadlift',
  'paused deadlift',
  'spoto press',
  'larsen press',
  'tempo bench',
  'tempo squat',
  'tempo deadlift',
  'stiffbar deadlift',
]

export const rpe = [
  [
    100.00,
    95.50,
    92.20,
    89.20,
    86.30,
    83.70,
    81.10,
    78.60,
    76.20,
    73.90,
    70.70,
    68.00,
  ],
  [
    97.80,
    93.90,
    90.70,
    87.80,
    85.00,
    82.40,
    79.90,
    77.40,
    75.10,
    72.30,
    69.40,
    66.70,
  ],
  [
    95.50,
    92.20,
    89.20,
    86.30,
    83.70,
    81.10,
    78.60,
    76.20,
    73.90,
    70.70,
    68.00,
    65.30,
  ],
  [
    93.90,
    90.70,
    87.80,
    85.00,
    82.40,
    79.90,
    77.40,
    75.10,
    72.30,
    69.40,
    66.70,
    64.00,
  ],
  [
    92.90,
    89.20,
    86.30,
    83.70,
    81.10,
    78.60,
    76.20,
    73.90,
    70.70,
    68.00,
    65.30,
    62.60,
  ],
  [
    90.70,
    87.80,
    85.00,
    82.40,
    79.90,
    77.40,
    75.10,
    72.30,
    69.40,
    66.70,
    64.00,
    61.30,
  ],
  [
    89.20,
    86.30,
    83.70,
    81.10,
    78.60,
    76.20,
    73.90,
    70.70,
    68.00,
    65.30,
    62.60,
    59.90,
  ],
  [
    87.80,
    85.00,
    82.40,
    79.90,
    77.40,
    75.10,
    72.30,
    69.40,
    66.70,
    64.00,
    61.30,
    58.60,
  ],
  [
    86.30,
    83.70,
    81.10,
    78.60,
    76.20,
    73.90,
    70.70,
    68.00,
    65.30,
    62.60,
    59.90,
    57.40,
  ],
]

export const testBlock = {
  'name': `gen-${getRandomInt(1000)}`,
  'id': '',
  'isProgram': false,
  'week': [
    {
      'name': 'test-template',
      'isTemplate': false,
      'day': [
        {
          'isRestDay': false,
          'exercise': [
            {
              'name': 'Heavy Squat',
              'lift': 'squat',
              'onerm': 86,
              'onermTop': 90,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 1,
              'notes': '1rm test',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'Deload Squat',
              'lift': 'squat',
              'onerm': 70,
              'onermTop': 75,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 6,
              'reps': 6,
              'notes': 'onec ac odio tempor orci. Aenean euismod elementum nisi quis eleifend q',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 1,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'Deficit Deadlift',
              'lift': 'deficit deadlift',
              'onerm': 90,
              'onermTop': 99,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': 8,
              'sets': 1,
              'reps': 2,
              'notes': 'por orci. Nunc sed augue lacus viverra. Sit amet nisl purus in mollis nunc sed id semper. Sollicitudin nibh sit amet commodo nulla facilisi nulla',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'rpe',
              'repUnit': '',
            },
            {
              'name': 'Deficit Deadlift',
              'lift': 'deficit deadlift',
              'onerm': 66,
              'onermTop': 70,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 8,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 3,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'run',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 4,
              'reps': 100,
              'notes': 'run repeats',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': 'meters',
            },
            {
              'name': 'Plank',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 30,
              'notes': 'planky planky planky',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': 'sec',
            },
          ],
        },
        {
          'isRestDay': false,
          'exercise': [
            {
              'name': 'Heavy Squat',
              'lift': 'squat',
              'onerm': 86,
              'onermTop': 90,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 1,
              'notes': '1rm test',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'Deload Squat',
              'lift': 'squat',
              'onerm': 70,
              'onermTop': 75,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 6,
              'reps': 6,
              'notes': 'onec ac odio tempor orci. Aenean euismod elementum nisi quis eleifend q',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 1,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'Deficit Deadlift',
              'lift': 'deficit deadlift',
              'onerm': 90,
              'onermTop': 99,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': 8,
              'sets': 1,
              'reps': 2,
              'notes': 'por orci. Nunc sed augue lacus viverra. Sit amet nisl purus in mollis nunc sed id semper. Sollicitudin nibh sit amet commodo nulla facilisi nulla',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'rpe',
              'repUnit': '',
            },
            {
              'name': 'Deficit Deadlift',
              'lift': 'deficit deadlift',
              'onerm': 66,
              'onermTop': 70,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 8,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 3,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'run',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 4,
              'reps': 100,
              'notes': 'run repeats',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': 'meters',
            },
            {
              'name': 'Plank',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 30,
              'notes': 'planky planky planky',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': 'sec',
            },
          ],
        },
        {
          'isRestDay': false,
          'exercise': [
            {
              'name': 'Heavy Squat',
              'lift': 'squat',
              'onerm': 86,
              'onermTop': 90,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 1,
              'notes': '1rm test',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'Deload Squat',
              'lift': 'squat',
              'onerm': 70,
              'onermTop': 75,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 6,
              'reps': 6,
              'notes': 'onec ac odio tempor orci. Aenean euismod elementum nisi quis eleifend q',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 1,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'Deficit Deadlift',
              'lift': 'deficit deadlift',
              'onerm': 90,
              'onermTop': 99,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': 8,
              'sets': 1,
              'reps': 2,
              'notes': 'por orci. Nunc sed augue lacus viverra. Sit amet nisl purus in mollis nunc sed id semper. Sollicitudin nibh sit amet commodo nulla facilisi nulla',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'rpe',
              'repUnit': '',
            },
            {
              'name': 'Deficit Deadlift',
              'lift': 'deficit deadlift',
              'onerm': 66,
              'onermTop': 70,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 8,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 3,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'run',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 4,
              'reps': 100,
              'notes': 'run repeats',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': 'meters',
            },
            {
              'name': 'Plank',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 30,
              'notes': 'planky planky planky',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': 'sec',
            },
          ],
        },
        {
          'isRestDay': true,
          'exercise': [],
        },
        {
          'isRestDay': false,
          'exercise': [
            {
              'name': 'Heavy Squat',
              'lift': 'squat',
              'onerm': 86,
              'onermTop': 90,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 1,
              'notes': '1rm test',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'Deload Squat',
              'lift': 'squat',
              'onerm': 70,
              'onermTop': 75,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 6,
              'reps': 6,
              'notes': 'onec ac odio tempor orci. Aenean euismod elementum nisi quis eleifend q',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 1,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'Deficit Deadlift',
              'lift': 'deficit deadlift',
              'onerm': 90,
              'onermTop': 99,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': 8,
              'sets': 1,
              'reps': 2,
              'notes': 'por orci. Nunc sed augue lacus viverra. Sit amet nisl purus in mollis nunc sed id semper. Sollicitudin nibh sit amet commodo nulla facilisi nulla',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'rpe',
              'repUnit': '',
            },
            {
              'name': 'Deficit Deadlift',
              'lift': 'deficit deadlift',
              'onerm': 66,
              'onermTop': 70,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 8,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 3,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'run',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 4,
              'reps': 100,
              'notes': 'run repeats',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': 'meters',
            },
            {
              'name': 'Plank',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 30,
              'notes': 'planky planky planky',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': 'sec',
            },
          ],
        },
        {
          'isRestDay': false,
          'exercise': [
            {
              'name': 'Heavy Squat',
              'lift': 'squat',
              'onerm': 86,
              'onermTop': 90,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 1,
              'notes': '1rm test',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'Deload Squat',
              'lift': 'squat',
              'onerm': 70,
              'onermTop': 75,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 6,
              'reps': 6,
              'notes': 'onec ac odio tempor orci. Aenean euismod elementum nisi quis eleifend q',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 1,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'Deficit Deadlift',
              'lift': 'deficit deadlift',
              'onerm': 90,
              'onermTop': 99,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': 8,
              'sets': 1,
              'reps': 2,
              'notes': 'por orci. Nunc sed augue lacus viverra. Sit amet nisl purus in mollis nunc sed id semper. Sollicitudin nibh sit amet commodo nulla facilisi nulla',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'rpe',
              'repUnit': '',
            },
            {
              'name': 'Deficit Deadlift',
              'lift': 'deficit deadlift',
              'onerm': 66,
              'onermTop': 70,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 8,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 3,
              'weightType': 'onerm',
              'repUnit': '',
            },
            {
              'name': 'run',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 4,
              'reps': 100,
              'notes': 'run repeats',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': 'meters',
            },
            {
              'name': 'Plank',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 30,
              'notes': 'planky planky planky',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': 'sec',
            },
          ],
        },
        {
          'isRestDay': true,
          'exercise': [],
        },
      ],
    },
  ],
}

export const testBlock2
  = {
  'name': 'SDAP1',
  'id': '',
  'isProgram': false,
  'week': [
    {
      'name': '',
      'isTemplate': false,
      'day': [
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'repUnit': '',
              'htmlLink': '',
              'isComplete': false,
            },
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'repUnit': '',
              'htmlLink': '',
              'isComplete': false,
            },
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'repUnit': '',
              'htmlLink': '',
              'isComplete': false,
            },
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 1,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 3,
              'weightType': 'onerm',
              'repUnit': 'AMRAP',
              'htmlLink': '',
              'isComplete': false,
            },
            {
              'name': 'Hyper Extension',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 10,
              'notes': 'Use weight',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': '',
              'htmlLink': '',
              'isComplete': false,
            },
            {
              'name': 'Pendulum Squat',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': '',
              'htmlLink': '',
              'isComplete': false,
            },
            {
              'name': 'Lying Hamstring Curls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': '',
              'htmlLink': '',
              'isComplete': false,
            },
            {
              'name': 'Ab Wheel',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': null,
              'repUnit': '',
              'htmlLink': '',
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': true,
          'isComplete': false,
          'exercise': [],
        },
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Block Press (Comp Grip)',
              'lift': 'bench',
              'onerm': 85,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 3,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Block Press (Comp Grip)',
              'lift': 'bench',
              'onerm': 80,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 3,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Cobra Lat Pulldown',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'htmlLink': 'https://www.youtube.com/shorts/lfIPgE1c9bQ',
              'isComplete': false,
            },
            {
              'name': 'Chest Supported Row',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Face Pulls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 15,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Dips',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Hammer Curls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 70,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 75,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 80,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 90,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 1,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 3,
              'weightType': 'onerm',
              'repUnit': 'AMRAP',
              'isComplete': false,
            },
            {
              'name': 'Hip Thrust',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Bulgarian Split Squats',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': 'Use weight',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'Reverse Lunges',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': 'Use weight',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'Farmers Carries',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 4,
              'reps': 30,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'Meters',
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': true,
          'isComplete': false,
          'exercise': [],
        },
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Bench',
              'lift': 'bench',
              'onerm': 75,
              'onermTop': 77,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 3,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'DB Shoulder Press',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': "I-Y-T's",
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 4,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'DB Lat Pullover',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Seated Row',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'DB Incline Tri Extensions',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Seated Incline DB Bicep Curls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': true,
          'isComplete': false,
          'exercise': [],
        },
      ],
    },
    {
      'name': '',
      'isTemplate': false,
      'day': [
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': 73,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': 77,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': 83,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': 90,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 1,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 3,
              'weightType': 'onerm',
              'repUnit': 'AMRAP',
              'isComplete': false,
            },
            {
              'name': 'Hyper Extension',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 10,
              'notes': 'Use weight',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Pendulum Squat',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Lying Hamstring Curls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Ab Wheel',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': true,
          'isComplete': false,
          'exercise': [],
        },
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Block Press (Close Grip)',
              'lift': 'bench',
              'onerm': 75,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Block Press (Close Grip)',
              'lift': 'bench',
              'onerm': 70,
              'onermTop': 72,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Cobra Lat Pulldown',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'htmlLink': 'https://www.youtube.com/shorts/lfIPgE1c9bQ',
              'isComplete': false,
            },
            {
              'name': 'Chest Supported Row',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Face Pulls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 15,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Dips',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Hammer Curls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 72,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 78,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 83,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 90,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 1,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 3,
              'weightType': 'onerm',
              'repUnit': 'AMRAP',
              'isComplete': false,
            },
            {
              'name': 'Hip Thrust',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Bulgarian Split Squats',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': 'Use weight',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'Reverse Lunges',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': 'Use weight',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'Farmers Carries',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 4,
              'reps': 30,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'Meters',
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': true,
          'isComplete': false,
          'exercise': [],
        },
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Bench',
              'lift': 'bench',
              'onerm': 77,
              'onermTop': 79,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 3,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'DB Shoulder Press',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': "I-Y-T's",
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 4,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'DB Lat Pullover',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Seated Row',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'DB Incline Tri Extensions',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Seated Incline DB Bicep Curls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': true,
          'isComplete': false,
          'exercise': [],
        },
      ],
    },
    {
      'name': '',
      'isTemplate': false,
      'day': [
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': 74,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': 80,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': 85,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': 90,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 1,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 3,
              'weightType': 'onerm',
              'repUnit': 'AMRAP',
              'isComplete': false,
            },
            {
              'name': 'Hyper Extension',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 10,
              'notes': 'Use weight',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Pendulum Squat',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Lying Hamstring Curls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Ab Wheel',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': true,
          'isComplete': false,
          'exercise': [],
        },
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Block Press (Comp Grip)',
              'lift': 'bench',
              'onerm': 88,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 3,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Block Press (Comp Grip)',
              'lift': 'bench',
              'onerm': 83,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 3,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Cobra Lat Pulldown',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'htmlLink': 'https://www.youtube.com/shorts/lfIPgE1c9bQ',
              'isComplete': false,
            },
            {
              'name': 'Chest Supported Row',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Face Pulls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 15,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Dips',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Hammer Curls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 75,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 80,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 85,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 90,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 1,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': 3,
              'weightType': 'onerm',
              'repUnit': 'AMRAP',
              'isComplete': false,
            },
            {
              'name': 'Hip Thrust',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Bulgarian Split Squats',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': 'Use weight',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'Reverse Lunges',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': 'Use weight',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'Farmers Carries',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 4,
              'reps': 30,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'Meters',
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': true,
          'isComplete': false,
          'exercise': [],
        },
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Bench',
              'lift': 'bench',
              'onerm': 79,
              'onermTop': 81,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 3,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'DB Shoulder Press',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': "I-Y-T's",
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 4,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'DB Lat Pullover',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Seated Row',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'DB Incline Tri Extensions',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Seated Incline DB Bicep Curls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 5,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': true,
          'isComplete': false,
          'exercise': [],
        },
      ],
    },
    {
      'name': '',
      'isTemplate': false,
      'day': [
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': 60,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': 65,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Squat',
              'lift': 'squat',
              'onerm': 70,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Hyper Extension',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 2,
              'reps': 10,
              'notes': 'Use Weight',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Pendulum Squat',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Lying Hamstring Curl',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Ab Wheel',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 2,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': true,
          'isComplete': false,
          'exercise': [],
        },
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Block Press (Close Grip)',
              'lift': 'bench',
              'onerm': 78,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Block Press (Close Grip)',
              'lift': 'bench',
              'onerm': 72,
              'onermTop': 74,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Cobra Lat Pulldown',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'Chest Supported Row',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Face Pulls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 15,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Dips',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Hammer Curls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 60,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 65,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Deadlift',
              'lift': 'deadlift',
              'onerm': 70,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 1,
              'reps': 6,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'Hip Thrust',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Bulgarian Split Squat',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'Reverse Lunge',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'Farmers Carries',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 2,
              'reps': 30,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'Meters',
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': true,
          'isComplete': false,
          'exercise': [],
        },
        {
          'isRestDay': false,
          'isComplete': false,
          'exercise': [
            {
              'name': 'Bench',
              'lift': 'bench',
              'onerm': 70,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 2,
              'reps': 3,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'weightType': 'onerm',
              'isComplete': false,
            },
            {
              'name': 'DB Shoulder Press',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': "I-Y-T's",
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 2,
              'reps': 8,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'repUnit': 'each',
              'isComplete': false,
            },
            {
              'name': 'DB Lat Pullover',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Seated Row',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'DB Incline Tri Extensions',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 12,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
            {
              'name': 'Seated Incline DB Bicep Curls',
              'lift': 'unlinked',
              'onerm': null,
              'onermTop': null,
              'weightTop': null,
              'weightBottom': null,
              'targetRpe': null,
              'sets': 3,
              'reps': 10,
              'notes': '',
              'isEstimatedOnerm': false,
              'estimatedOnermIndex': null,
              'isComplete': false,
            },
          ],
        },
        {
          'isRestDay': true,
          'isComplete': false,
          'exercise': [],
        },
      ],
    },
  ],
}
