import { type AppType } from "next/app";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  RedirectToSignIn,
} from "@clerk/nextjs";
import { Provider } from "jotai";
import Head from "next/head";
import Layout from "~/components/layout";

import { api } from "~/utils/api";

import "~/styles/globals.css";
import { Toaster } from "react-hot-toast";

const MyApp: AppType = ({ Component, pageProps }) => {
  return (
    <Provider>
      <ClerkProvider {...pageProps}>

        <Head>
          <title>Create T3 App</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <SignedOut>
          <RedirectToSignIn />
        </SignedOut>
        <SignedIn>
          <Layout>
            <Component {...pageProps} />
          </Layout>
        </SignedIn>

        <Toaster 
          position="bottom-center" 
          toastOptions={{
            style: {
              background: '#333',
              color: '#fff',
            },
          }}
        />
      </ClerkProvider>
    </Provider>
  )

};

export default api.withTRPC(MyApp);
